# Generated by Django 3.0.6 on 2020-05-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('E', 'Enfermo'), ('N', 'Negativo'), ('C', 'Curado'), ('F', 'Fallecido'), ('EE', 'En espera'), ('A', 'Aislado')], default='N', help_text='Estado en que se encuentra el paciente', max_length=2)),
                ('asintomatico', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
